# Generated by Django 5.2.5 on 2025-08-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users_image'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
