# Generated by Django 5.2.5 on 2025-08-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='modified_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
